manifest:
  remotes:
    - name: Broken-Spear
      url-base: https://github.com/YK7ROS/zmk-config-Broken-Spear/actions/runs/7751949004/job/21140645476
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: Broken-Spear
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
